### Hyper Parameters ###
# Whether to only measure the time of the algorithm
time_only: False

# Whether to profile the code. (Takes longer time ~2x)
profile: False

# Whether to display a replay of the last game played
replay: 0 # 0: no replay, 1: replay the last game, 2: replay the last game with display

# Save games to pickle file
#save: "../saved_games" # default to Othello-Reversi/saved_games/
save: False

# Path to statistics file
stats_path: "../stats.csv" # default to Othello-Reversi/stats.csv

# Number of games
n: 20

### Game Parameters ###
# Who plays against who.
# 0: human.
# 1: random (chooses randomly a possible move),
# 2: positional. (uses a heuristic table to define the quality of a position),
# 3: absolute (minimizes/maximizes the number of pieces for the opponent/player),
# 4: mobility (minimizes/maximizes the number of possible moves for the opponent/player),
# 5: mixed (uses a heuristic table to define the quality of a position). Mixed signifies using positional, then mobility, then absolute.
mode: [5, 2]

# Which MiniMax version to use.
# 0: Default MiniMax
# 1: Alpha-Beta pruning
# 2: Default Negamax
# 3: Alpha-Beta pruning Negamax
minimax_mode: [3, 3]

# Maximum depth of the search tree (minimax algorithm)
max_depth: [6, 6]

# Which heuristic table to use.
# 0: Default if mode is 2 or 6, else None
# 1: TABLE1
# 2: TABLE2
h_table: [1, 1]

# Threshold for when to switch strategies if mode is 6. 
threshold: [15, 45] # Default = [15, 45]

# Size of the board
size: 8 # The program is not yet fully tested with other sizes than 8

# Whether to display the board with a graphical interface
display: False

# Whether to print the result of a game
verbose: 0  # Verbose levels : 0: no print, 1: print only the result, 2: print the result and the boards after each turn
